### ISSUE TITLE
Trees have weird protein identifiers

### ISSUE THREAD

**Issue by sammyjava** [legumeinfo/datastore-issues#104]
I've come to the realization that I'm storing standalone empty proteins in the mines because the trees have non-LIS-compliant identifiers, for example in L_001QTQ the first one is **arahy.86RVGQ.1** which doesn't really correspond to anything in the Datastore. Yes, there is a arahy.Tifrunner.gnm1.ann1.86RVGQ.1 but I can't merge those without doing extra work which I don't think is appropriate.

For now I'll skip loading trees. I would think the trees are built with proteins from specific genome assemblies and annotations in any case. Maybe you've @adf-ncgr mentioned the need to full-yuckify the trees already.

**Comment by adf-ncgr** [comment]
Yes, we have fully yucked versions of the trees and associated files here:
/usr/local/www/data/private/Gene_families/YUCKIFIED_legume.genefam.fam1.M65K
One minor-ish thing to be aware of is that I recently became aware that the medicago proteins that I had labeled as medtr.A17_HM341.gnm4.ann2 seem to actually correspond to medtr.A17_HM341.gnm4.ann1 which we don't actually
have in the datastore. As far as I can tell the main difference between the two versions is that some isoforms that were present in v1 were subsequently dropped from v2, which is how I came to realize the discrepancy between the trees and what's in the rest of LIS. It seems to be relatively uncommon to find a protein in the trees corresponding to an isoform that was dropped, so I'm thinking we probably don't want to load v1 just to cover these rare events. Hopefully we'll build new families (or at least new trees representing the same families) before too long.

**Comment by sammyjava** [comment]
Well keeping with the "only load what's in the public datastore" policy I'll wait until full-yuck trees appear on the public DS. I don't think the trees are a big deal since I can link off to them elsewhere in the LIS solar system.

**Comment by adf-ncgr** [comment]
Is my assignment to move the files to the public area of the datastore?

**Comment by sammyjava** [comment]
Yes, and by doing so bless them with whatever water you choose.

**Comment by adf-ncgr** [comment]
OK, the fully-yucked versions are now in place at /usr/local/www/data/v2/LEGUMES/Fabaceae/genefamilies/legume.genefam.fam1.M65K
note that this includes full-yuck for outgroup species, I'm not sure if there is data for any of these other than in the proteomes included with the families but just be aware that we'll have things like arath.Col.gnm9.ann10.AT5G02490.1
and solly.Heinz1706.gnm2_5.ann2_4.Solyc00g059100.2.1 (the latter being a little weird in that tomato gene models have .num suffixes, making their isoforms .num.num - extra nummy!) 
anyway, I hope this will fix issues, but I wouldn't be surprised if some naming skew has crept in for some of the legume species since I original made this, so tread carefully. I'll leave this open until we are satisfied that things are loading properly

**Comment by adf-ncgr** [comment]
@sammyjava did you ever get a chance to look at the blessed yuck here? (just taking a quick look at issues assigned to me and looks like I will re-assign this to you)

**Comment by sammyjava** [comment]
Ah yeah, did right away on June 10. Thanks!
