### ISSUE TITLE
some Medicago GFAs have different protein names from FASTAs

### ISSUE THREAD

**Issue by sammyjava** [legumeinfo/datastore-issues#105]
Example:

A17.gnm5.ann1_6.L2RX/medtr.A17.gnm5.ann1_6.L2RX.legfed_v1_0.M65K.gfa.tsv:
```
medtr.A17.gnm5.ann1_6.MtrunA17Chr5g0404241    legfed_v1_0.L_KLD4T6    medtr.A17.gnm5.ann1_6.mRNA:MtrunA17Chr5g0404241      7.8e-244        810.3   810.1
```
A17.gnm5.ann1_6.L2RX/medtr.A17.gnm5.ann1_6.L2RX.phytozome_10_2.HFNR.gfa.tsv:
```
medtr.A17.gnm5.ann1_6.MtrunA17Chr5g0404241 59258104        medtr.A17.gnm5.ann1_6.mRNA:MtrunA17Chr5g0404241      3.3e-226        752.3   752.2
```
A17.gnm5.ann1_6.L2RX/medtr.A17.gnm5.ann1_6.L2RX.protein.faa:
```
>medtr.A17.gnm5.ann1_6.MtrunA17Chr5g0404241.1 len=421 type=prot strand=- chr=MtrunA17Chr5 gn=MtrunA17Chr5g0404241 begin=7822970 end=7829518 def=Putative GTP-binding protein Era
```
This, of course, creates stranded proteins in the mine with gene family associations but nothing else, e.g.
```
 primaryaccession | description |    id    | length | genefamilyscore | name |                primaryidentifier                | genefamilyscoremeaning |           md5checksum            | molecularweight | symbol | assemblyversion | annotationversion | isprimary |    secondaryidentifier    | phylonodeid | transcriptid |  cdsid   | organismid | sequenceid | genefamilyid | strainid |              class              
------------------+-------------+----------+--------+-----------------+------+-------------------------------------------------+------------------------+----------------------------------+-----------------+--------+-----------------+-------------------+-----------+---------------------------+-------------+--------------+----------+------------+------------+--------------+----------+---------------------------------
                  |             | 38280900 |        |        3.3e-226 |      | medtr.A17.gnm5.ann1_6.mRNA:MtrunA17Chr5g0404241 |                        |                                  |                 |        | gnm5            | ann1_6            |           | mRNA:MtrunA17Chr5g0404241 |             |              |          |    2000002 |            |     38126114 |  2000003 | org.intermine.model.bio.Protein
                  |             | 38029947 |    421 |                 |      | medtr.A17.gnm5.ann1_6.MtrunA17Chr5g0404241.1    |                        | 963a26a1128d4e9f4f8af2dbccc55c2f |                 |        | gnm5            | ann1_6            |           | MtrunA17Chr5g0404241.1    |             |     38029949 | 38029946 |    2000002 |   38347247 |              |  2000003 | org.intermine.model.bio.Protein
```
Please double-check that GFAs and FASTAs have the same protein identifiers (and GFAs and GFFs have same gene identifiers) across the board, since _this breaks a mine load_. I'll reload MedicMine after this is fixed.

**Comment by adf-ncgr** [comment]
should be fixed now; was also an issue in the iprscan.gff3 file

**Comment by sammyjava** [comment]
Thanks. FWIW this is why I make proteins have gene.n identifiers, so I can populate the Protein.genes collection (and vice-versa). I don't know of another way to make this reliable; the GFA file has only one protein per gene and there is no other file that relates proteins to genes that I know of. But if you think of a better way than syntax to associate genes with proteins, I'm all ears.
```java
    /**
     * Return a gene ID as the portion of an ID with the .1, .2, etc. removed
     *
     * @param dotId the dot.number ID
     * @return the corresponding gene ID
     */
    static String getGeneIdFromDotId(String dotId) {
        String[] parts = dotId.split("\\.");
        String geneId = parts[0];
        for (int i=1; i<parts.length-1; i++) geneId += "."+parts[i];
        return geneId;
    }
```

**Comment by adf-ncgr** [comment]
Well, we have a policy (specified somewhere, though whereabouts of the assertion currently unremembered) that proteins are id'd identically to the transcripts from which they are derived (and so for example we strip the .p suffixes off that phytozome uses to make their protein ids unique and distinct from the transcript ids). 

With this in mind, the gff file becomes the key to linking them, since the transcript is linked to the gene explicitly there. There is at least one dataset (https://data.legumeinfo.org/Trifolium/pratense/annotations/MilvusB.gnm2.ann1.DFgp) where the connection between transcript and gene is not "obvious" from the naming; e.g. (from the gfa file):


#gene | family | protein | e-value | score
-- | -- | -- | -- | --
tripr.MilvusB.gnm2.ann1.gene8659 | legfed_v1_0.L_01FS7B | tripr.MilvusB.gnm2.ann1.mRNA8951 | 9.8E-30 | 105.1
tripr.MilvusB.gnm2.ann1.gene14036 | legfed_v1_0.L_0GZG6J | tripr.MilvusB.gnm2.ann1.mRNA14503 | 2E-123 | 413.7
tripr.MilvusB.gnm2.ann1.gene1606 | legfed_v1_0.L_FJ1R08 | tripr.MilvusB.gnm2.ann1.mRNA1634 | 3.2E-39 | 135.0

so I wonder how you have dealt with this one in the past?

**Comment by sammyjava** [comment]
Ah, right, yeah, I used to run a post-processor to do the relate-to-what's-related thing, which got to take forever so I switched to establishing the connections in the loader, but with the errant assumption of gene.n. So I'll switch to using the GFF relationships now, since I"m loading both protein FASTA and GFF in the same loader (lis-annotation) and can actually do it; this was not possible before that fairly recent change when I loaded all FASTAs separately. Thanks for the reminder.
