### ISSUE TITLE
information under Arachis/GENUS needs review in order to pass muster for loading into PeanutMine

### ISSUE THREAD

**Issue by adf-ncgr** [legumeinfo/datastore-issues#17]
@sammyjava says we need to clean this up; for example, the current taxid given is actually for hypogaea, and the current species name is "sp" which doesn't match the folder name GENUS. I thought the latter was an accepted special case but perhaps not.

**Comment by sammyjava** [comment]
Genomes must be loaded as gensp.strain.gnm.ann.foo files and located under a v2/Genus/species folder. Taxon ID must uniquely identify the species. So:

1. a species name must be invented (e.g. "sp", "synth", etc.) which must lead to a unique _gensp_
2. a strain name must be invented (because strain assemblies/annotations are loaded into the mines)
3. a taxonomy ID that is not currently in NCBI must be invented (NOT the ID for the genus, that has an existing meaning and should not be used for a synthetic strain)

In that case, one loads the synthetic strain genome just as one loads real strains.

**Comment by adf-ncgr** [comment]
I guess the thing that prompted this was really the markers dataset:
https://legumeinfo.org/data/v2/Arachis/GENUS/markers/mixed.mrk.Axiom_Arachis_58K_SNP/
which as I understand it is mapped to a synthetic combination of araip and aradu genomes
(which itself doesn't actually "exist" as a genome in the datastore).

**Comment by sammyjava** [comment]
Yeah, that doesn't even seem like something worth having in the DS. Just create Axiom_Arachis_58K_SNP GFFs for each actual genome. I don't think there's any extra information in this file. The flanking sequences can be put into GFF attributes.

**Comment by adf-ncgr** [comment]
works for me, but it's not my file of markers. Were there things that needed to be discussed about the interspecific maps? Is there a reason those shouldn't reference the "genus" as their "organism"?

**Comment by sammyjava** [comment]
InterMine Organism is at the species level. It has a genus and species, neither of which can be null, nor can the taxonId be null.

**Comment by sammyjava** [comment]
The interspecific maps are a problem, one solution would be to yank the organism reference from GeneticMap. I don't think there's any strong functional reason to have GeneticMap.organism. (Note that README.genotypes get loaded as populations, for historical reasons, there is a very simple Population class that just holds the string.)

  [ ] Genetic Map 
     -   [ ] Description
     -   [ ] Genotyping Platform
     -   [ ] LIS Identifier
     -   [ ] Synopsis
     -   [+] Data Sets Data Set  ?
     -   [+] Linkage Groups Linkage Group 
     -   [+] Organism Organism  ?
     -   [+] Populations Population 
     -   [+] Publications Publication  ?
     -   [+] Qtls QTL

**Comment by sammyjava** [comment]
I guess that would also mean dropping QTL.organism. Marker.organism can be left empty with these loads, which will get populated when the marker GFF gets loaded for the particular genome, as long as there is only one. Otherwise, we'll hit a merge collision on that marker. Probably best to always use marker maps to hypogaea in the Arachis case, or give them different names for the different GFFs.

**Comment by sammyjava** [comment]
On that topic, another really core-level change would be to have a non-SequenceFeature GeneticMarker class and then a SequenceFeature to which it is related (via collection) called, say, GenomicMarker. Then we can load any genomes and have the GeneticMarker "map" to those genomes via the related "GenomicMarker." That adds an extra step, but if we want multiple genomes in the mines with markers mapped to them, we pretty much have to do this.

**Comment by cann0010** [comment]
I think it's not inappropriate (conceptually) to have sequences that belong to a genus. Both repeat sequences and genetic markers are valid examples. Sure, we could assign them, post-hoc, a particular accession; but they should be applicable across most everything in the genus, and may have been identified as common elements from many accessions. I don't want to exclude them from the Data Store; the repeats, in particular, are quite important for annotation projects.

They could be excluded from the Mine ... or maybe your solution, Sam (put them in a non-SequenceFeature class).

**Comment by sammyjava** [comment]
I'm talking about what can be loaded into the mines. We can have all sorts of non-mine-compliant files in the DS.

As for genetic markers, I've been avoiding this discussion until the files got nailed down. Since I need to merge markers from genetic files (with just the marker name) with markers in genomic files (full yuck) and we may have those markers mapped to multiple genomes, there probably is no way around separating GeneticMarker from GenomicMarker in the mines.

But that's a loader issue now, the files are all set. The question is just when I make that change and rebuild -- now, or after I get all the files sorted for all the genus mines and, finally, LegumeMine. Since the file curation is a bigger job, I've been focusing on that.

Oh and I'm moving this to a new issue because it's a different issue, I shouldn't have typed about it under this issue.

**Comment by adf-ncgr** [comment]
@cann0010 agreed that having certain things assigned at a genus level is not conceptually inappropriate (probably no more so than species, anyway- species don't have genomes, individuals have genomes, etc.). 

I would like to better understand the plan for representing repeat data. The current situation is a little confusing to me; e.g. we have repeat fastas under both GENUS/repeats and hypogaea/repeats but from the sequence names it's not clear the latter are really species-specific since they have both Ah and Ad named elements; also the former seem to have a sort of full-yuck applied but the latter do not. Per a peanutbase user request I just posted a gff file of repeatmasker output which I posted to annotations, but it would probably be good for us to agree that this is indeed the right place for it (and not under repeats folder for example). Perhaps this is worth its own issue.

Incidentally, the new RepeatModeler2 tool seems to be doing a fair job and is relatively easy to run on genomes, so have been considering the value of doing something a bit more systematic than we currently have. But, I don't necessarily see all the ramifications of such a plan. An agenda item for another week...

**Comment by sammyjava** [comment]
> @cann0010 agreed that having certain things assigned at a genus level is not conceptually inappropriate (probably no more so than species, anyway- species don't have genomes, individuals have genomes, etc.).

Well, ya know, there's certain things about species -- like the same number of chromosomes and things, that make a species-level genome a BIT more sensible than a genus-level genome. But, I veer toward practicality, something LIS maybe isn't particularly concerned with.

**Comment by sammyjava** [comment]
> I would like to better understand the plan for representing repeat data. The current situation is a little confusing to me; e.g. we have repeat fastas under both GENUS/repeats and hypogaea/repeats but from the sequence names it's not clear the latter are really species-specific since they have both Ah and Ad named elements; also the former seem to have a sort of full-yuck applied but the latter do not. Per a peanutbase user request I just posted a gff file of repeatmasker output which I posted to annotations, but it would probably be good for us to agree that this is indeed the right place for it (and not under repeats folder for example). Perhaps this is worth its own issue.

Yes, clearly it is a separate issue. Please make it so. (You'll find Reference in new issue in the three-dot menu.)

**Comment by sammyjava** [comment]
I'm closing this for now. I don't see any actionable "solution" to an issue. Reopen with a specific issue and assignee if appropriate.
