### ISSUE TITLE
Wm82_ISU01.gnm2.JFPQ question

### ISSUE THREAD

**Issue by jd-campbell** [legumeinfo/datastore-issues#197]
Hello @StevenCannon-USDA 

During the SBW meeting we found out that the seed for Wm82_ISU01 -- was given a specific PI from GRIN (PI 704477). I was thinking that we should have this info in the README. 
My question is where and (should we) add the PI number to the README?

**Comment by adf-ncgr** [comment]
Hi Jacqueline-
currently we seem to store PI numbers in a structured way in:
Glycine/max/about_this_collection/description_Glycine_max.yml
(field "accession")
but they also often appear as keywords or in descriptive text in the README files. I suppose since each "strain" may appear in multiple collections, centralizing this type of structured info may make sense.

As to when you add it, no time like the present...

adf

**Comment by StevenCannon-USDA** [comment]
I agree with @adf-ncgr about where to add it. It would go into both the genomes and annotations README, and `description_Glycine_max.yml`.

I'm logged in; I can take care of it now.

**Comment by jd-campbell** [comment]
Thank you.

**Comment by StevenCannon-USDA** [comment]
Added to the genomes and annotations READMEs:
```
description: "This release (Glycine max var. Williams 82-ISU-01) is an inbred line developed 
by Robert Stupar (University of Minnesota) by inbreeding original W82 seed, PI 704477. ...
```
Revised in `about_this_collection/description_Glycine_max.yml`:
```
identifier: Wm82_ISU01
accession: PI 704477
```

These won't take effect at Jekyll-SoyBase until we update the datastore-metadata submodule.
