### ISSUE TITLE
Underscore rather than dash in CDS files in Vigna/unguiculata/annotations/CB5-2.gnm1.ann1.0GKC

### ISSUE THREAD

**Issue by cann0010** [legumeinfo/datastore-issues#55]
In this collection:
/usr/local/www/data/v2/Vigna/unguiculata/annotations/CB5-2.gnm1.ann1.0GKC
the following files have "vigun.CB5_2" rather than "vigun.CB5-2"
vigun.CB5-2.gnm1.ann1.0GKC.cds_primaryTranscript.fna 
vigun.CB5-2.gnm1.ann1.0GKC.cds.fna 
vigun.CB5-2.gnm1.ann1.0GKC.protein.faa 
vigun.CB5-2.gnm1.ann1.0GKC.transcript_primaryTranscript.fna 
vigun.CB5-2.gnm1.ann1.0GKC.transcript.fna

These forms are incompatible with the GFF and BED names.

I propose s/vigun.CB5_2.gnm1.ann1/vigun.CB5-2.gnm1.ann1/ for these.

Objections - @sammyjava @adf-ncgr @ctcncgr ?

**Comment by sammyjava** [comment]
Imperative. In fact, it's even worse. CowpeaMine got loaded funky because the CDS FASTA identifiers are, for example:
```
>vigun.CB5_2.gnm1.ann1.VuCB5-2.L000100.1
>vigun.CB5_2.gnm1.ann1.VuCB5-2.L000100.2
```
while the corresponding GFF identifiers are:
```
ID=vigun.CB5-2.gnm1.ann1.VuCB5-2.L000100.1.CDS.1;
ID=vigun.CB5-2.gnm1.ann1.VuCB5-2.L000100.1.CDS.2;
ID=vigun.CB5-2.gnm1.ann1.VuCB5-2.L000100.2.CDS.1;
ID=vigun.CB5-2.gnm1.ann1.VuCB5-2.L000100.2.CDS.2;
ID=vigun.CB5-2.gnm1.ann1.VuCB5-2.L000100.2.CDS.3;
```
This led to the FASTA CDS being stranded, not associated with their GFF-derived versions. That's OK, if we'd like the FASTA CDSes to stand on their own but they should still have the same prefix!

So not only are the yuck prefixes inconsistent, but the actual identifiers are inconsistent (perhaps intentionally).

As per our discussion this morning, @ctcncgr is compiling a list of things that I catch (and don't catch, clearly) when loading the DS data into the mines for a QC application. The DS is still a minefield of errors. These files should have triggered a loud beeper and flashing red lights. There are boatloads of closed issues on this repo for things that @adf-ncgr fixed for me as I was loading the mines, but we've only had mine loading to raise flags, and sometimes flags don't get raised -- the mine is just broken as a result.

**Comment by adf-ncgr** [comment]
CB5-2 is correct. I think confusion came from the fact that the phytozome download files use CB5_2 in the file names. Sounds like not only the file names are needing to be fixed but also the fasta headers. I will self-assign and get it done today.

**Comment by adf-ncgr** [comment]
looks like maybe @cann0010 got to the file renaming first, but I've now corrected the fasta headers too. closing
