### ISSUE TITLE
glyma.Wm82.gnm2.div.Lee_Jeong_2015.SNPdata.vcf.gz is broken

### ISSUE THREAD

**Issue by sammyjava** [legumeinfo/datastore-issues#63]
```
> Task :dbmodel:loadSingleSource
Loading Wm82.gnm2.div.Lee_Jeong_2015 tgt items into production DB
 [dataLoad] [Execution worker for ':' Thread 6] INFO com.zaxxer.hikari.HikariDataSource - db.production - Starting...
 [dataLoad] [Execution worker for ':' Thread 6] INFO com.zaxxer.hikari.HikariDataSource - db.production - Start completed.
 [dataLoad] Processing README.Wm82.gnm2.div.Lee_Jeong_2015.yml
 [dataLoad] Processing glyma.Wm82.gnm2.div.Lee_Jeong_2015.SNPdata.vcf.gz

> Task :dbmodel:loadSingleSource FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':dbmodel:loadSingleSource'.
> htsjdk.tribble.TribbleException$MalformedFeatureFile: Unable to parse header with error: Your input file has a malformed header: Unexpected tag INFO in line <INFO=rs####,Number=1,Type=String,Description="dbSNP_ID">, for input source: file:///data/v2/Glycine/max/diversity/Wm82.gnm2.div.Lee_Jeong_2015/glyma.Wm82.gnm2.div.Lee_Jeong_2015.SNPdata.vcf.gz
```

**Comment by adf-ncgr** [comment]
I believe instead of:
##FORMAT=<INFO=rs####,Number=1,Type=String,Description="dbSNP_ID">
it ought to be
##INFO=<ID=rs####,Number=1,Type=String,Description="dbSNP_ID">

But the actual records would also need to be updated to have the "tag" part of tag=value, ie rs####=rs121991268 
instead of just rs121991268 as they currently have. I'm not personally in love with rs#### as a tag, although as far as I can tell it is legal. It appears that the recommended use of dbSNP ids is to have them in the ID field when available and to tag them as such in the INFO field with a DB attribute that has no corresponding value. I'm not sure I like that so much, especially given how non-privileged dbSNP is when it comes to non-human variants (they unprivileged themselves). I guess this VCF file actually corresponds to a SNP array and it seems appropriate to have the primary IDs given with respect to that array as is currently done. I propose we change the rs#### to dbSNP and fix accordingly (I can do if no one objects to this change).

**Comment by adf-ncgr** [comment]
I believe I've fixed the issues per my suggestion above (also there are some records on the chloroplast sequence which was missing from the header, probably since it isn't really part of glyma.Wm82.gnm2). In any case, the VCF is now convertible to bcf by bcftools, which I'm guessing is going to satisfy the htsjdk as well/
