### ISSUE TITLE
Duplicate markers for common bean

### ISSUE THREAD

**Issue by svengato** [legumeinfo/datastore-issues#64]
The following marker files are identical except for the second column, so we should remove one of them. Note that the corresponding GWAS dataset matches the latter collection name ('Y' instead of 'y' between 'Mier' and 'Teran').

/v2/Phaseolus/vulgaris/markers/G19833.gnm1.mrk.Parker_BernyMieryTeran_2020/phavu.G19833.gnm1.mrk.Parker_BernyMieryTeran_2020.gff3.gz

/v2/Phaseolus/vulgaris/markers/G19833.gnm1.mrk.Parker_BernyMierYTeran_2020/phavu.G19833.gnm1.mrk.Parker_BernyMierYTeran_2020.gff3.gz

**Comment by sammyjava** [comment]
Deleted the lower-case "y" version. This came from a Steven decision on how to deal with some foreign names, the upper-case "Y" makes it clear that the author's name is Mier, not Miery. (While the first author's name is Berny, not Bern.) I suppose we'll do the same thing with "de" and "von", etc.

@nathanweeks I cannot blow away the folder because of a stale NFS handle. Please remove and delete the dir.
```
[shokin@lis-stage ~/v2/Phaseolus/vulgaris/markers]$ ls -f G19833.gnm1.mrk.Parker_BernyMieryTeran_2020/
.                     ..                    .nfs.bd485499.5ada4.4
```

**Comment by nathanweeks** [comment]
Done.
