### ISSUE TITLE
Missing data for mixed.gen.Burridge_Schneider_2017

### ISSUE THREAD

**Issue by svengato** [legumeinfo/datastore-issues#65]
For cowpea QTL data in v2/Vigna/unguiculata/genetic/mixed.gen.Burridge_Schneider_2017/

1. Markers listed in vigun.mixed.gen.Burridge_Schneider_2017.qtlmrk.tsv.gz are not found in Vigna/unguiculata/markers/IT97K-499-35.gnm1.mrk.Cowpea1MSelectedSNPs/vigun.IT97K-499-35.gnm1.mrk.Cowpea1MSelectedSNPs.gff3.gz

2. In vigun.mixed.gen.Burridge_Schneider_2017.obo.tsv.gz, some traits have no ontology code.

**Comment by sammyjava** [comment]
I put in the parent terms for stuff that's missing in the TO like "Root Tip Abundance" (RTA). Unless there's an ontology term for the Rochester Transit Authority.

**Comment by svengato** [comment]
Point 1 (missing Burridge-Schneider markers) is still unresolved.

**Comment by sammyjava** [comment]
@cann0010 is there a source for the missing Cowpea1MSelectedSNPs marker maps to vigun.IT97K-499-35.gnm1? Otherwise we'll just close this, we can't create data that don't exist. Here's what's in the qtlmrk file:
```
13772_1075
5084_519
4836_807
10811_937
2326_226
12501_343
139_439
5061_428
7102_965
1004_587
8969_1386
2227_693
9645_589
5428_339
3211_511
4749_1972
11138_624
14604_737
13848_735
11851_914
4245_136
2391_614
```

**Comment by cann0010** [comment]
Some sleuthing: It's not the IT97K-499-35.gnm1.div.Huynh_Ehlers_2018 diversity set, which has only 32k markers.
Skimming the paper ...
Burridge JD, Schneider HM, Huynh BL, Roberts PA, Bucksch A, Lynch JP. Genome-wide association mapping and agronomic impact of cowpea root architecture. Theor Appl Genet. 2017 Feb;130(2):419-431. doi: 10.1007/s00122-016-2823-y. Epub 2016 Nov 18. PMID: 27864597.
... the markers come from 
Lucas MR, Diop N-N, Wanamaker S, Ehlers JD, Roberts PA, Close TJ
(2011) Cowpea–soybean synteny clarified through an improved
genetic map. Plant Genome 4:218–225
https://acsess.onlinelibrary.wiley.com/doi/full/10.3835/plantgenome2011.06.0019

... which traces back to Muchero et al, 2009
10.1073/pnas.0905886106

YES: Supplement for that Muchero et al paper (tsp file attached; derived from manuscript supplement 0905886106_SD1.xls)
[0905886106_SD1.txt](https://github.com/legumeinfo/datastore-issues/files/7960670/0905886106_SD1.txt)

**Comment by adf-ncgr** [comment]
thanks @cann0010! just glancing at the file it looks like at least some of the qtlmrk markers correspond to SNPs in the Cowpea1MSelectedSNPs, using the column 1 (SNP) as the match, e.g. 13772_1075 from the list above -> 1_0749 which is in the 1M set. Think it's legit to substitute the SNP ids for the "marker" ids in the qtlmrk file? Seems better to me to do so, but let me know if you agree with this change and I can make it so.

**Comment by sammyjava** [comment]
What matters is that the identifier in the qtlmarker file is the Name attribute of the marker in the GFF. That's how they're merged. Otherwise it'll be stranded markers with no genomic location.

**Comment by sammyjava** [comment]
(There are likely marker GFFs that will show up as issues because they don't have full-yuck ID attributes and short-name Name attributes, although I'll typically fix those myself.)

**Comment by adf-ncgr** [comment]
only 17 out of the 22 SNPs can be found in the 1M set; so we may have to get genomic locations for the others by mapping the sequences. Since they are not all in the 1M set, perhaps we should just treat them as their own little marker collection?

**Comment by sammyjava** [comment]
Fine with me, be sure to update README.genotyping_platform with your new name if/when you do.

**Comment by adf-ncgr** [comment]
OK, probably won't get to it for a while, but will re-assign to myself (though others are welcome to wrest it back)

**Comment by sammyjava** [comment]
*ping* @adf-ncgr

**Comment by adf-ncgr** [comment]
OK, I haven't actually gotten any farther on this, but it reminds about an issue I wanted to raise in general. Our current marker specification is all about the markers in the context of a genome. This is useful to be sure, but may be problematic in cases where markers are specified as flanking sequence and some of those sequences have not yet been anchored uniquely in a genome. For example (the ones that got me thinking about this when a user asked about alfalfa marker sequences):
https://alfalfatoolbox.org/filebrowser/download/175
https://alfalfatoolbox.org/filebrowser/download/176
Since mapping marker sequences to a genome "B" may not produce the same result as mapping marker sequences to genome "A" then projecting them to "B" by means of aligning A->B (especially for those that don't map to A in the first place), it may be useful to formalize a marker sequence fasta convention as well as the gff3 representation. We may already have some non-formal examples of this such as https://data.legumeinfo.org/Arachis/GENUS/markers/mixed.mrk.Axiom_Arachis_58K_SNP/

FWIW, I know that the cowpea group has been assiduously reviewing the mappings represented in https://data.legumeinfo.org/Vigna/unguiculata/markers/IT97K-499-35.gnm1.mrk.Cowpea1MSelectedSNPs/
using the flanking sequences from the chip design and will likely publish an updated version (though I'm pretty sure the ones I failed to find in the current mapping will still not be present, since I think they were not from the chip).

**Comment by cann0010** [comment]
About formalizing "a marker sequence fasta convention as well as the gff3 representation": I agree that these should be accommodated, though I imagine this as an optional extra file type -- probably either just a standard fasta file with marker names as the fasta IDs, or with alleles specified with e.g. "[A/G] at the variant site. I believe we have one such marker file in the DS currently (I am surprised we don't have more).
Phaseolus/vulgaris/genetic/mixed.gen.Blair_Cortés_2018/phavu.mixed.gen.Blair_Cortés_2018.flanking_seq.fna.gz

**Comment by adf-ncgr** [comment]
Thanks @cann0010 ! I was also a bit surprised we don't have more, although I did find a couple of others using some find-based guesswork:
./Cajanus/cajan/markers/mixed.mrk.1drZ/cajca.mixed.mrk.1drZ.cajan_v2_primers.txt.gz
./Arachis/GENUS/markers/mixed.mrk.Axiom_Arachis_58K_SNP/arachis.mixed.mrk.Axiom_Arachis_58K_SNP.flank_seq.tsv.gz
note that the former is primer sequence pairs, similar to one of the alfalfa example whereas the arachis one is more like [A/G] at the variant site (although not as fasta).

anyway, because this representation would be genome-independent, I'm imagining it would live separate from the marker gffs (as in the above examples, but probably under markers rather than genetic?); and then gff marker mapping files derived using it would be as we currently have them, probably with some explicit reference to the sequence collection in their README. I think we'll be getting some more alfalfa markers from the Breeding Insight group and would like to handle them in some similar way, so we can figure out a good protocol for dealing with mapping to the growing number of autotetraploid genomes.

**Comment by sammyjava** [comment]
But also, @adf-ncgr you're really good at hijacking issues, which is not an instant messaging app. So please if you have a new issue like "what to do with marker sequences" create a new one rather than hijacking this one. Much appreciated. I'll do so with these posts.

**Comment by adf-ncgr** [comment]
thanks, you're right.

**Comment by sammyjava** [comment]
I think this got sorted out over time. Or we'll create a fresh issue but I've got VignaMine loaded and running.
