### ISSUE TITLE
Medicago/truncatula/diversity/ lacks README

### ISSUE THREAD

**Issue by sammyjava** [legumeinfo/datastore-issues#69]
Handy benefit of having the READMEs in a repo is that git status shows the collections that don't have them! Here's one:

Medicago/truncatula/diversity/

**Comment by adf-ncgr** [comment]
I suppose you mean the folders under Medicago/truncatula/diversity/
these will get READMEs when they are fully conformant in other respects, they are only there now to fulfill a gap in availability since the downloads of the old medicago hapmap site went away unexpectedly early. will leave open, but won't get action immediately

**Comment by adf-ncgr** [comment]
these now have READMEs. I think I even validated them...
