### ISSUE TITLE
Synteny files that reference nonexistent chromosomes should be removed

### ISSUE THREAD

**Issue by sammyjava** [legumeinfo/datastore-issues#75]
IMO these two synteny files should be removed from the Datastore. They reference nonexistent chromosomes, plus, they have non-conformant filenames and identifiers within those files. (You don't get to add an extra dot-delimited portion within filenames or identifiers.)
```
Glycine/max/synteny/Wm82.gnm2.ann1.syn.HXNY/
├── glyma.Wm82.gnm2.ann1.x.glyma.Wm82.gnm2.ann1.old_duplication.HXNY.gff3.gz
├── glyma.Wm82.gnm2.ann1.x.glyma.Wm82.gnm2.ann1.recent_duplication.HXNY.gff3.gz
```
If you do want to reference those other chromosomes, you need to give them a conformant name (e.g. glyma.Wm82.gnm2.ann1OD.Gm18, glyma.Wm82.gnm2.ann1RD.Gm18) and create /genomes/ FASTAs to define them. Those collections will explain in the README what you mean by "old duplication" and "recent duplication".

**Comment by adf-ncgr** [comment]
I agree these files ought to be tweaked a bit, but would propose a different solution. 
Here's a current record:
`glyma.Wm82.gnm2.ann1.Gm01	DAGchainer	syntenic_region	227021	926129	1243.0	+	.	Name=glyma.Wm82.gnm2.ann1.old_duplication.Gm08;matches=glyma.Wm82.gnm2.ann1.old_duplication.Gm08:2159073..2752670;median_Ks=0.7982`

Column one I think ought to simply be glyma.Wm82.gnm2.Gm01 which is a valid chromosome. The Name of the feature seems like an OK place to denote that it is "old duplication", and I guess the Name can be non-unique if we don't care. Not sure if the absence of ID is going to cause issues. But I think the "matches" ought to be changed to Target=glyma.Wm82.gnm2.Gm08 2159073 2752670 which the way gff3 denotes pairwise relationships between sequences (and which I thought was being used in our other synteny files, although I haven't paid much attention to them since GCV started generating macrosynteny on the fly). 

my 2c, but @cann0010 is the authority on these files.

**Comment by sammyjava** [comment]
There is no chromosome in the Datastore called glyma.Wm82.gnm2.ann1.old_duplication.Gm08, which isn't an allowable name for a chromosome (gensp.gnm.ann.Name without dots within Name).  So it makes no sense to call any SequenceFeature that, and SyntenicRegion extends SequenceFeatures.

If the two SyntenicRegions are on glyma.Wm82.gnm2.ann1.Gm01 and glyma.Wm82.gnm2.ann1.Gm08, then they are syntenic regions on those two chromosomes and should be called as such. You don't get to add "Fred" or "Ginger" to identifiers just because you feel like it.

I'm closing this and will simply not load those two files. I will only load SyntenicRegions on chromosomes that exist. I think the files should be deleted as utterly non-conformant but this isn't worth discussing any further.
