### ISSUE TITLE
Soybean 'genetic' files missing header line

### ISSUE THREAD

**Issue by svengato** [legumeinfo/datastore-issues#94]
For other species, these have a header like (for .obo.tsv)
#Trait	OntologyIdentifier
but the headers are missing for soybean. This concerns .obo.tsv, .result.tsv, .qtl.tsv, .qtlmrk.tsv, etc.

**Comment by sammyjava** [comment]
The header isn't required. Do you require it? I'm happy to punch it in if so.

**Comment by svengato** [comment]
Headers would be good, in order to be consistent with the other species' data files. I will also check whether the R code can detect headers on the fly (I think you have to know in advance though). Thanks -

**Comment by sammyjava** [comment]
OK you're all set, headers added. AND the lg.tsv and mrk.tsv files are now under /maps/ with the genetic map name:
```
├── mixed.map.GmComposite1999
│   ├── glyma.mixed.map.GmComposite1999.lg.tsv.gz
│   ├── glyma.mixed.map.GmComposite1999.mrk.tsv.gz
│   └── README.mixed.map.GmComposite1999.yml
├── mixed.map.GmComposite2003
│   ├── glyma.mixed.map.GmComposite2003.lg.tsv.gz
│   ├── glyma.mixed.map.GmComposite2003.mrk.tsv.gz
│   └── README.mixed.map.GmComposite2003.yml
...
```
The README files in each genetic collection now reference the map with the new `genetic_map` attribute, e.g.
```
---
identifier: Zhongdou27_x_Jiunong20.gen.Zeng_Li_2009
genetic_map: GmComposite2003
provenance: SoyBase
source: "https://soybase.org/"
synopsis: "Identification of QTL underlying isoflavone contents in soybean seeds among multiple environments"
scientific_name: Glycine max
taxid: 3847
scientific_name_abbrev: glyma
genotype:
  - Zhongdou 27 x Jiunong 20
description: "Further information provided in 10.1007/s00122-009-0994-5"
publication_doi: 10.1007/s00122-009-0994-5
publication_title: "Identification of QTL underlying isoflavone contents in soybean seeds among multiple environments"
contributors: "Guoliang Zeng, Dongmei Li, Yingpeng Han, Weili Teng, Jian Wang, Liquan Qiu, Wenbin Li"
public_access_level: public
license: Open
```
I'll be updating other species according to the new spec, starting with phavu.

**Comment by svengato** [comment]
It looks good, the only anomaly I notice is that
  https://data.legumeinfo.org/Glycine/max/genetic/mixed.gwas.Dhanapal_Ray_2016/
contains both
  glyma.mixed.gwas.Dhanapal_Ray_2016.[obo, result].tsv.gz
(which seems correct) and
  glyma.mixed.gwas.Dhanapal_Ray_1111.[obo, result].tsv.gz
(lacking the header - I can delete them if you like)

**Comment by svengato** [comment]
It looks good, the only anomaly I notice is that
  https://data.legumeinfo.org/Glycine/max/genetic/mixed.gwas.Dhanapal_Ray_2016/
contains both
  glyma.mixed.gwas.Dhanapal_Ray_2016.[obo, result].tsv.gz
(which seems correct) and
  glyma.mixed.gwas.Dhanapal_Ray_1111.[obo, result].tsv.gz
(lacking the header - I can delete them if you like)

**Comment by svengato** [comment]
One more problem - somehow the non-header lines in the .qtl files ended up with an extra tab between the next to last and last columns, which messes up the table. Example (glyma.Conrad_x_OX760-6-1.gen.Han_Teng_2008.qtl.tsv):

#qtl_identifier	trait_name	linkage_group	start	end	peak
Phytoph 10-3	Phytoph	GmComposite2003_D1b	111.04	116.34	113.69		29.77				
Phytoph 10-2	Phytoph	GmComposite2003_F	3.04	5.56	4.3		28.67				
Phytoph 10-1	Phytoph	GmComposite2003_F	0.0	5.05	2.53		28.99

**Comment by svengato** [comment]
Never mind, on closer examination it should not matter.

**Comment by adf-ncgr** [comment]
I think it's because the full set of headers is not there to give meaning to empty columns;
per qtl spec they are (ie the values in the last column are LOD scores):
QTL identifier
trait name
linkage group
start (cM)
end (cM)
peak (cM)
favored allele source
LOD
likelihood ratio
marker r2
total r2
additivity

**Comment by sammyjava** [comment]
Correct, I only have headers for columns that exist. Optional columns are optional, are are headers for those optional columns. In fact, the header is optional in general. I never expected the header to be a critical thing since the columns are defined in the spec.

And yeah delete the 1111 files, those were temp files that got carried over.

**Comment by sammyjava** [comment]
Feel free to do anything with the header lines that you like. :)

**Comment by svengato** [comment]
Deleted the 1111 files.

**Comment by svengato** [comment]
There is still something wrong with the soybean QTL files, but it may be on my end.

**Comment by sammyjava** [comment]
Be sure to take into account the mrk.tsv and lg.tsv files have moved over to /maps/.

**Comment by svengato** [comment]
Got it. But the ZZBrowse process does not use those.

**Comment by adf-ncgr** [comment]
I personally feel like having headers is a good idea. If nothing else, it helps (albeit imperfectly) track what version of a spec a file is trying to conform to. Since we don't formally version our specs, such a method may be as good as anything else we're likely to cook up. Plus it just seems more user-friendly to give headers than to say "RTFS"; even with GFF3 I find myself trying to remember without looking it up whether strand is supposed to go in field 6 or 7 (not the greatest example since it's generally easy to look for the field containing  + or - but hopefully it makes the point)

**Comment by svengato** [comment]
I see the problem - the qtlmrk file format has changed! The columns used to be (and still are for most species)
  identifier marker
but since a week ago (commit dc4acd4), it has been
  identifier trait_name marker

**Comment by sammyjava** [comment]
Indeed, that was necessitated by collections that lack a qtl.tsv file and didn't have traits associated with the QTL-marker associations. Always check the spec when you're wondering what's going on, and yes, I don't update the entire datastore with the new spec, that happens as I roll through new mine builds and edit the files so they load.

**Comment by sammyjava** [comment]
And @adf-ncgr sounds fine to me, I'll add them as required in the specs and fill them in as I go. You guys can do the same if you find them missing.
